### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by selankon** [vocdoni/saas-backend#7]
After doing a signup I tried to login without success: 

```
➜ curl 'https://saas-dev.vocdoni.app/auth' -X POST  --data-raw '{"email":"misa@tusa.com","password":"12345678"}'
404 page not found
```

Two issues here: 

- Login is not possible
- The error message for an unsuccessful login shouldn't be 404 (on the API docs the expected error is another also)

**Comment by p4u** [comment]
@emmdim consider upgrading the docs of the API if required

**Comment by emmdim** [comment]
@selankon  you are not pointing to the right endpoint. The correct route is `auth/login`
The error message is a router level message that indicates that the route does not exists.

Can you try again using the correct endpoint?
